config/routes.rb
Rubyroots::Application.routes.draw do

  resources :meetups

  resources :gitgems

  resources :tasks

  devise_for :users

  root :to => 'home#index'
  match '/home' => 'home#index'

end

app/models/gitgem.rb
class Gitgem < ActiveRecord::Base
  attr_accessible :description, :name, :version
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  attr_accessible :date, :description, :direction, :place
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gitgems_controller.rb
class GitgemsController < ApplicationController
  before_filter :authenticate_user!
  # GET /gitgems
  # GET /gitgems.json
  def index
    @gitgems = Gitgem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gitgems }
    end
  end

  # GET /gitgems/1
  # GET /gitgems/1.json
  def show
    @gitgem = Gitgem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gitgem }
    end
  end

  # GET /gitgems/new
  # GET /gitgems/new.json
  def new
    @gitgem = Gitgem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gitgem }
    end
  end

  # GET /gitgems/1/edit
  def edit
    @gitgem = Gitgem.find(params[:id])
  end

  # POST /gitgems
  # POST /gitgems.json
  def create
    @gitgem = Gitgem.new(params[:gitgem])

    respond_to do |format|
      if @gitgem.save
        format.html { redirect_to @gitgem, notice: 'Gitgem was successfully created.' }
        format.json { render json: @gitgem, status: :created, location: @gitgem }
      else
        format.html { render action: "new" }
        format.json { render json: @gitgem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gitgems/1
  # PUT /gitgems/1.json
  def update
    @gitgem = Gitgem.find(params[:id])

    respond_to do |format|
      if @gitgem.update_attributes(params[:gitgem])
        format.html { redirect_to @gitgem, notice: 'Gitgem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gitgem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gitgems/1
  # DELETE /gitgems/1.json
  def destroy
    @gitgem = Gitgem.find(params[:id])
    @gitgem.destroy

    respond_to do |format|
      format.html { redirect_to gitgems_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
	def index
		
	end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_filter :authenticate_user!
  # GET /meetups
  # GET /meetups.json
  def index
    @meetups = Meetup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetups }
    end
  end

  # GET /meetups/1
  # GET /meetups/1.json
  def show
    @meetup = Meetup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meetup }
    end
  end

  # GET /meetups/new
  # GET /meetups/new.json
  def new
    @meetup = Meetup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meetup }
    end
  end

  # GET /meetups/1/edit
  def edit
    @meetup = Meetup.find(params[:id])
  end

  # POST /meetups
  # POST /meetups.json
  def create
    @meetup = Meetup.new(params[:meetup])

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render json: @meetup, status: :created, location: @meetup }
      else
        format.html { render action: "new" }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetups/1
  # PUT /meetups/1.json
  def update
    @meetup = Meetup.find(params[:id])

    respond_to do |format|
      if @meetup.update_attributes(params[:meetup])
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup = Meetup.find(params[:id])
    @meetup.destroy

    respond_to do |format|
      format.html { redirect_to meetups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gitgems_helper.rb
module GitgemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gitgems/_form.html.erb
<%= form_for @gitgem, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :version, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :version, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gitgems_path, :class => 'btn' %>
  </div>
<% end %>

app/views/gitgems/edit.html.erb
<%- model_class = Gitgem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gitgems/index.html.erb
<%- model_class = Gitgem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:version) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gitgems.each do |gitgem| %>
      <tr>
        <td><%= link_to gitgem.id, gitgem_path(gitgem) %></td>
        <td><%= gitgem.name %></td>
        <td><%= gitgem.description %></td>
        <td><%= gitgem.version %></td>
        <td><%=l gitgem.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gitgem_path(gitgem), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gitgem_path(gitgem),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gitgem_path,
            :class => 'btn btn-primary' %>

app/views/gitgems/new.html.erb
<%- model_class = Gitgem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gitgems/show.html.erb
<%- model_class = Gitgem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @gitgem.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @gitgem.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:version) %>:</strong></dt>
  <dd><%= @gitgem.version %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gitgems_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gitgem_path(@gitgem), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gitgem_path(@gitgem),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<h2>Welcome to RubyRoots</h2>

<h3>Home of the Garden Route Ruby User Group</h3>

Join us @ 
<a href='https://groups.google.com/forum/?fromgroups#!forum/rubyroots'>rubyroots google group</a>
<br />
Jump right in @
<a href='https://github.com/QuentinLangeveldt/rubyroots'>rubyroots github repo</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyroots</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="#">RubyRoots</a>
    <div class="nav-collapse collapse">
      <ul class="nav">
        <li class="active">
          <%= link_to '', root_path, data: {}, :class => 'icon-home', :title => 'home' %>
        </li>
        <li>          
          <%= link_to '', meetups_path, data: {}, :class => 'icon-share', :title => 'meetups' %>
        </li>
        <li>
          <%= link_to '', gitgems_path, data: {}, :class => 'icon-github', :title => 'gems' %>
        </li>       
      </ul>
    </div>
    <div id='user_nav' class='pull-right-2'>
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you? <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "signin", new_user_session_path %>.
      <% end %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/meetups/_form.html.erb
<%= form_for @meetup, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :date, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :place, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :place, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :direction, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :direction, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                meetups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<%- model_class = Meetup -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meetups/index.html.erb
<%- model_class = Meetup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:direction) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @meetups.each do |meetup| %>
      <tr>
        <td><%= link_to meetup.id, meetup_path(meetup) %></td>
        <td><%= meetup.date %></td>
        <td><%= meetup.description %></td>
        <td><%= meetup.place %></td>
        <td><%= meetup.direction %></td>
        <td><%=l meetup.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_meetup_path(meetup), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      meetup_path(meetup),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_meetup_path,
            :class => 'btn btn-primary' %>

app/views/meetups/new.html.erb
<%- model_class = Meetup -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meetups/show.html.erb
<%- model_class = Meetup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @meetup.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @meetup.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @meetup.place %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direction) %>:</strong></dt>
  <dd><%= @meetup.direction %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              meetups_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_meetup_path(@meetup), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              meetup_path(@meetup),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>